" Execute the following line in a shell:
" curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
" https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
" Use :PlugInstall after adding plugins

call plug#begin('~/.vim/plugged')
Plug 'chase/vim-ansible-yaml'
Plug 'lepture/vim-jinja'
Plug 'Yggdroot/indentLine'
Plug 'ekalinin/Dockerfile.vim'
Plug 'andrewstuart/vim-kubernetes'
Plug 'elzr/vim-json'
Plug 'preservim/nerdcommenter'
Plug 'preservim/nerdtree'
Plug 'noah/vim256-color'
Plug 'gu-fan/riv.vim'
call plug#end()

" Look and Feel
colorscheme atom-dark
syntax on
set number
set cursorline
set ruler
set laststatus=2
set tabstop=4 
set softtabstop=4 
set shiftwidth=4 
set expandtab 
set smarttab 
set textwidth=80
set nowrap

" Backspace behaviour
set backspace=indent,eol,start
