# Antigen, make sure git is installed and execute:
# curl -L git.io/antigen > ~/antigen.zsh

source ~/.antigen.zsh
antigen use oh-my-zsh
antigen bundle woefe/vi-mode.zsh
antigen bundle woefe/wbase.zsh
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-completions
antigen bundle git
antigen bundle git-hub
antigen bundle git-prompt
antigen theme bira
antigen apply

# General Options
setopt autocd
setopt nonomatch
setopt notify
setopt numericglobsort
setopt promptsubst

# History
HISTFILE=~/.zsh_history
HISTSIZE=1000
SAVEHIST=2000
setopt INC_APPEND_HISTORY
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_REDUCE_BLANKS
setopt HIST_VERIFY

# Variables
export EDITOR=/usr/bin/vim
